---
title: "Per Read Analysis"
author: "José Miguel Ramírez"
date: "30/4/2019"
fontsize: 12pt
output: 
  pdf_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning = FALSE)
```

```{r libraries, eval=TRUE}
#Rscript -e "rmarkdown::render(input='per_read_analysis.Rmd')" -t 5000 -i final_output_RNA081120181_NM_curlcake,final_output_m6A_final -n "NM,M6A"

#Rscript -e "rmarkdown::render(input='per_read_analysis.Rmd')" -t 500 -i final_output_RNAAB063141,final_output_RNAAB064293 -n "0 % DMS,0.5 % DMS"

library(ggplot2)
library(grid)
library(gridExtra)
require(reshape2)
library("RColorBrewer")
library(ggpubr)
library(optparse)
```


&nbsp;

```{r parser, eval=TRUE}
parser <- OptionParser()
parser <- add_option(parser, opt_str=c("-t", "--threshold"), type="integer",
                     dest='threshold', default=500,
                     help="This parameters is an integer specifying an upper threshold for removing outliers")
parser <- add_option(parser, opt_str=c("-i", "--inputs"), type="character",
                     dest='inputs',
                     help="Comma separated list of files (without blank spaces)")
parser <- add_option(parser, opt_str=c("-n", "--inputname"), type="character",
                     dest='names', 
                     help="String with comma separated list of titles of files")

options=parse_args(parser)

threshold=options$threshold
#threshold=500
names=options$names
#names="0 % DMS,0.5 % DMS"
inputs=options$inputs
#inputs="final_output_RNAAB063141,final_output_RNAAB064293"
myfilelist <- strsplit(inputs, ",")
n=length(myfilelist[[1]])
myfilenames <- strsplit(names, ",")

```

# `r myfilenames[[1]]`

```{r SEQ_ID}
tables <- list()
for (i in seq(n)){
  tables[[paste("tab",i,sep = "")]] <- read.table(myfilelist[[1]][i], header = T)}
  
update_list <- function(i){
  i <- i[i$alignment_length<500,]
  return(i)}

tables <- lapply(tables, update_list)

sequence_identity <- function(table, name, y){
  g <- ggplot(table, aes(seq_id)) + geom_density() + theme_bw() + xlab("") + geom_vline(xintercept = mean(table$seq_id), colour="red") + ggtitle(name) + annotate("text", x = mean(table$seq_id)-4, y = y, label = "mean", color="red", angle=90)
  return(g)
}

l <- list()
for (i in seq(n)){
  g <- sequence_identity(tables[[i]], myfilenames[[1]][i], 0.01)
  l[[i]] <- g
}

grid.arrange(grobs=l, nrow=1, top=grid.text("Sequence Identity", gp=gpar(fontface="bold")))
```

We are removing reads with length higher than `r threshold` bp.


```{r READ_LENGTH}
#quality is missing, indels is missing
dats <- list()
for (i in seq(n)){
  dats[[paste("dat",i,sep = "")]] <- melt(tables[[i]][,c(1,2,3)])
  }

read_length <- function(data, name){
  g <- ggplot(data, aes(variable, value)) + geom_boxplot(colour=c("#F8766D","#00BFC4")) + theme_bw() + xlab("") + ggtitle(name) #+ ylim(0,500)
  return(g)}

l <- list()
for (i in seq(n)){
  g <- read_length(dats[[i]], myfilenames[[1]][i])
  l[[i]] <- g}

grid.arrange(grobs=l, nrow=1, top=grid.text("Read Lengths", gp=gpar(fontface="bold")))
```


```{r, results='asis'}
for (i in seq(n)){
  cat(paste(myfilenames[[1]][i]),":  \n")
  cat(paste("fold change:", round(mean(dats[[i]][dats[[i]]$variable=="guppy_length",]$value)/mean(dats[[i]][dats[[i]]$variable=="albacore_length",]$value), 4), "  \n"))
  p <- wilcox.test(value ~ variable,  data = dats[[i]], paired = TRUE)$p.value
  cat(paste("Wilcoxon test p.value:", p , "  \n"))
  cat(paste("  \n"))
}

```


\clearpage

```{r, results='asis'}
smalltabs <- list()
for (i in seq(n)){
  smalltabs[[paste("dat",i,sep = "")]] <- tables[[i]][,c(1,2,3)]
}

par(mfrow=c(1,n))
for(i in seq(n)){
  dcols<-densCols(smalltabs[[i]]$albacore_length, smalltabs[[i]]$guppy_length, colramp=colorRampPalette(blues9[-(1:4)]))
  plot(smalltabs[[i]]$albacore_length, smalltabs[[i]]$guppy_length,col=dcols,cex=1, cex.lab=1, cex.main=1,lwd=5,pch=20, xlab = "Albacore Length", ylab="Guppy Length", main = paste(myfilenames[[1]][i], "Read Length"))
  abline(0,1)
  
}

for (i in seq(n)){
cat(paste("Spearman's rank correlation rho for", myfilenames[[]][i], "is", round(cor.test(smalltabs[[i]]$albacore_length, smalltabs[[i]]$guppy_length, method = "spearman", exact = FALSE)$estimate, 4), "  \n"))
}

```

```{r READ_LENGTH_DENSITY}

read_density <- function(data, name){
  g <- ggplot(data, aes(value, colour=variable)) + geom_density() + theme_bw() + xlab("Read Lengths") + ggtitle(name) + theme(legend.title=element_blank()) + scale_color_manual(labels = c("Albacore  ", "Guppy"), values = c("#F8766D", "#00BFC4"))
  return(g)
}

l <- list()
for (i in seq(n)){
  g <- read_density(dats[[i]], myfilenames[[1]][i])
  l[[i]] <- g}

figure <- ggarrange(plotlist=l, ncol=2, nrow=1, common.legend = TRUE, legend="bottom")
annotate_figure(figure, top = text_grob("Read Length Density", face = "bold"))

```


```{r GAPS}

dats <- list()
for (i in seq(n)){
  dats[[paste("dat",i,sep = "")]] <- melt(tables[[i]][,c(1,7,8)])
  }

gaps <- function(data, name){ #, lim
  g <- ggplot(data, aes(variable, value)) + geom_boxplot(col=c("#F8766D", "#00BFC4")) + theme_bw() + xlab("") + ylab("Number of Gaps") + ggtitle(name) #+ ylim(0,lim)
  return(g)
}

l <- list()
for (i in seq(n)){
  g <- gaps(dats[[i]], myfilenames[[1]][i]) #, threshold
  l[[i]] <- g}

grid.arrange(grobs=l, nrow=1, top=grid.text("Number of Gaps", gp=gpar(fontface="bold")))
```

```{r, results='asis'}
for (i in seq(n)){
  cat(paste(myfilenames[[1]][i]),":  \n")
  cat(paste("fold change:", round(mean(dats[[i]][dats[[i]]$variable=="gaps_guppy",]$value)/mean(dats[[i]][dats[[i]]$variable=="gaps_albacore",]$value), 4), "  \n"))
  p <- wilcox.test(value ~ variable,  data = dats[[i]], paired = TRUE)$p.value
  cat(paste("Wilcoxon test p.value:", p , "  \n"))
  cat(paste("  \n"))
}

```

```{r}
gaps_density <- function(data, name){ #, lim
  g <- ggplot(data, aes(value, colour=variable)) + geom_density() + theme_bw() + xlab("Number of Gaps") + theme(legend.title=element_blank()) + scale_color_manual(labels = c("Albacore  ", "Guppy"), values = c("#F8766D", "#00BFC4")) + ggtitle(name) #+ xlim(0, lim)
  return(g)
}

l <- list()
for (i in seq(n)){
  g <- gaps_density(dats[[i]], myfilenames[[1]][i]) #, 200
  l[[i]] <- g
}

figure <- ggarrange(plotlist=l, ncol=2, nrow=1, common.legend = TRUE, legend="bottom")
annotate_figure(figure, top = text_grob("Number of Gaps Density", face = "bold"))

```


```{r INDELS}

dats <- list()
for (i in seq(n)){
  dats[[paste("dat",i,sep = "")]] <- melt(tables[[i]][,c(1,12,13)])
  }

indels <- function(data, name){ #, lim
  g <- ggplot(data, aes(variable, value)) + geom_boxplot(col=c("#F8766D", "#00BFC4")) + theme_bw() + xlab("") + ylab("Number of Indels") + ggtitle(name) #+ ylim(0,lim)
  return(g)
}

l <- list()
for (i in seq(n)){
  g <- indels(dats[[i]], myfilenames[[1]][i]) #, threshold
  l[[i]] <- g}

grid.arrange(grobs=l, nrow=1, top=grid.text("Number of Indels", gp=gpar(fontface="bold")))
```

```{r INDELS2, results='asis'}
for (i in seq(n)){
  cat(paste(myfilenames[[1]][i]),":  \n")
  cat(paste("fold change:", round(mean(dats[[i]][dats[[i]]$variable=="deletions",]$value)/mean(dats[[i]][dats[[i]]$variable=="insertions",]$value), 4), "  \n"))
  p <- wilcox.test(value ~ variable,  data = dats[[i]], paired = TRUE)$p.value
  cat(paste("Wilcoxon test p.value:", p , "  \n"))
  cat(paste("  \n"))
}

```

&nbsp;  

N consecutive gaps in albacore are considered as one insertion, and N number of consecutive gaps in guppy are considered as one deletion.

```{r INDELS3}
indels_density <- function(data, name){ #, lim
  g <- ggplot(data, aes(value, colour=variable)) + geom_density() + theme_bw() + xlab("Number of Indels") + theme(legend.title=element_blank()) + scale_color_manual(labels = c("Insertions", "Deletions"), values = c("#F8766D", "#00BFC4")) + ggtitle(name) #+ xlim(0, lim)
  return(g)
}

l <- list()
for (i in seq(n)){
  g <- indels_density(dats[[i]], myfilenames[[1]][i]) #, 200
  l[[i]] <- g
}

figure <- ggarrange(plotlist=l, ncol=2, nrow=1, common.legend = TRUE, legend="bottom")
annotate_figure(figure, top = text_grob("Number of Indels Density", face = "bold"))

```

```{r GAPS_5_PRIME}

dats <- list()
for (i in seq(n)){
  dats[[paste("dat",i,sep = "")]] <- melt(tables[[i]][,c(1,10,11)])
  }

gaps_5 <- function(data, name){
  g <- ggplot(data, aes(variable, value)) + geom_boxplot(col=c("#F8766D", "#00BFC4")) + theme_bw() + xlab("") + ylab("Number of Gaps") + ggtitle(name)
  return(g)
}

l <- list()
for (i in seq(n)){
  g <- gaps_5(dats[[i]], myfilenames[[1]][i]) 
  l[[i]] <- g}

grid.arrange(grobs=l, nrow=1, top=grid.text("Number of Gaps in 5'", gp=gpar(fontface="bold")))
```


```{r, results='asis'}
for (i in seq(n)){
  cat(paste(myfilenames[[1]][i]),":  \n")
  cat(paste("fold change:", round(mean(dats[[i]][dats[[i]]$variable=="gaps_guppy_50",]$value)/mean(dats[[i]][dats[[i]]$variable=="gaps_albacore_50",]$value), 4), "  \n"))
  p <- wilcox.test(value ~ variable,  data = dats[[i]], paired = TRUE)$p.value
  cat(paste("Wilcoxon test p.value:", p , "  \n"))
  cat(paste("  \n"))
}

```

```{r}
smalltabs <- list()
for (i in seq(n)){
  smalltabs[[paste("dat",i,sep = "")]] <- tables[[i]][,c(1,10,11)]
}
par(mfrow=c(1,2))
for(i in seq(n)){
  dcols<-densCols(smalltabs[[i]]$gaps_albacore_50, smalltabs[[i]]$gaps_guppy_50, colramp=colorRampPalette(blues9[-(1:3)]))
  plot(jitter(smalltabs[[i]]$gaps_albacore_50), smalltabs[[i]]$gaps_guppy_50,col=dcols,cex=1, cex.lab=1, cex.main=1,lwd=5,pch=20, xlab = "Gaps Albacore 5'", ylab="Gaps Guppy 5'", main = myfilenames[[1]][i])
}
par(mfrow=c(1,n))


```
